### PR TITLE
Add dest dir option

### PR DESCRIPTION
**Pull request by mbrevda**

### CODE REVIEW

**Comment by mbrevda** [comment]
ping?

**Comment by leipert** [comment]
Hey there, sorry. I didn't see this Issue. Next time mention me :dancer:

**Comment by leipert** [comment]
@mbrevda 
You should really unset WERCKER_GIT_PUSH_DESTDIR at the end of your script.
(f69a75a3151cc012567396cd13c5080dbeac5c3e)
In the following wercker.yml the first git-push would set a destdir and the second would still have it set as wercker does not reset env variables between steps.

``` yaml
    - git-push:
         ...
         destdir: foo
    - git-push:
         ...
```

**Comment by mbrevda** [comment]
Thanks for merging @leipert , I'd rather not host yet another fork!

 [There is one more fix thats needed](https://github.com/mbrevda/step-git-push/commit/d444df3018a31bf62fe6de154f0c27ea2520ce9e/run.sh) to ensure the directory structure exists before trying to copy files there.

**Comment by mbrevda** [comment]
As an aside, so you think it would be feasible to an an option that can select only specific source files?

**Comment by leipert** [comment]
Actually no, I just move all files I want at the server to a defined src folder before.

**Comment by leipert** [comment]
This is an example configuration I use:

``` yaml
box: leipert/ubuntu14.04-webessentials@2.0.1
# Build definition
build:
  # The steps that will be executed on build
  steps:
    # A step that executes `npm install` command
    - script:
        name: Copying config
        code: cp $CONFIG_FILE app/overwrite.js
    - npm-install
    - leipert/yeoman-bower-install
    - script:
        name: Test and build gsb
        code: gulp
    - script:
        name: Copying config
        code: mkdir -p dist/config && cp -r config/* dist/config/


deploy:
  steps:
    - leipert/git-push:
         gh_token: $GH_TOKEN
         gh_pages: true
         basedir: dist
         discard_history: false
    - leipert/git-push:
         gh_token: $GH_TOKEN
         host: github.com
         repo: leipert/gsb
         branch: dist
         basedir: dist
         tag: bower
         tag_overwrite: true
```

**Comment by leipert** [comment]
Fixed with #4

**Comment by mbrevda** [comment]
Duh, copying first should have been obvious! Thanks!

**Comment by leipert** [comment]
No problem :)

Sometimes it really speeds up your builds if you delete all unneeded files as last build step as wercker does not to copy node_modules and other stuff to the deployment steps.

``` yaml
    - script:
        name: Copying config
        code: mkdir -p dist/config && cp -r config/* dist/config/
    - script:
        name: Cleanup build output
        code: ls -A | grep -v dist | xargs rm -rf
```

**Pull request merged**
